apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-certmanager
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/xtrasolver/talos-backup.git
      targetRevision: HEAD
      ref: repo
    - repoURL: "https://charts.jetstack.io"
      chart: cert-manager
      targetRevision: 1.12.3
      helm:
        releaseName: certmanager
        valueFiles:
          - $repo/infra/values/certmanager.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: certmanager
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
