apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-rook-operator
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/xtrasolver/talos-backup.git
      targetRevision: HEAD
      ref: repo
    - repoURL: https://charts.rook.io/release
      chart: rook-ceph
      targetRevision: 1.13.2
      helm:
        releaseName: rook-ceph
        valueFiles:
          - $repo/infra/values/rook-operator.yaml
    - repoURL: https://github.com/xtrasolver/talos-backup.git
      targetRevision: HEAD
      path: infra/resources/rook-operator
  destination:
    server: "https://kubernetes.default.svc"
    namespace: rook-ceph
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true