apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: apps.my-lab.cz
  namespace: ingress
spec:
  dnsNames:
    - "*.apps.home.my-lab.cz"
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-cert-issuer
  secretName: apps.my-lab.cz
  usages:
    - digital signature
    - key encipherment