apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: secrets-backup
  annotations:
    argocd.argoproj.io/sync-wave: "5"    
spec:
  # backup once per day at 0:00
  schedule: "0 0 * * *"
  template:
    labelSelector:
      matchExpressions:
      - {key: velero-backup, operator: In, values: ['true']}
    excludedNamespaces: []
    includedResources:
    - '*'
    storageLocation: minio