global:
  addPrometheusAnnotations: true
server:
  ingress:
    enabled: true
    hosts: 
      - argocd.apps.home.my-lab.cz
    tls:
    - hosts:
        - argocd.apps.home.my-lab.cz
    https: true
    ingressClassName: "nginx"
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/ssl-passthrough: "false"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"      