server:
  ingress:
    enabled: true
    hosts: 
      - argocd.apps.home.my-lab.cz
    tls:
    - hosts:
        - argocd.apps.home.my-lab.cz
    https: true
    ingressClassName: "nginx"
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/ssl-passthrough: "false"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      interval: 30s
      selector:
        release: kube-prometheus-stack
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 10m
      memory: 64Mi        
controller:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      interval: 30s
      selector:
        release: kube-prometheus-stack
  resources:
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 50m
      memory: 512Mi        
repoServer:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      interval: 30s
      selector:
        release: kube-prometheus-stack
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 256Mi        
applicationSet:
  enabled: false
dex:
  enabled: false
notifications:
  enabled: false
redis:
  resources:
    limits:
      cpu: 100m
      memory: 64Mi
    requests:
      cpu: 10m
      memory: 32Mi  