tenant:
  secrets:
    existingSecret: minio-tenant
  name: myminio
  pools:
  - servers: 1
    name: pool-0
    volumesPerServer: 4
    size: 10Gi
    storageClassName: openebs-jiva-csi-default
ingress:
  api:
    enabled: true
    ingressClassName: "nginx"
    labels: { }
    annotations:
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/ssl-passthrough: "false"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"    
    host: myminio.apps.home.my-lab.cz
    tls:
    - hosts:
        - myminio.apps.home.my-lab.cz
    path: /
    pathType: Prefix
  console:
    enabled: true
    ingressClassName: "nginx"
    labels: { }
    annotations:
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/ssl-passthrough: "false"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"    
    host: myminio-console.apps.home.my-lab.cz
    tls:
    - hosts:
        - myminio-console.apps.home.my-lab.cz
    path: /
    pathType: Prefix
