resources:
  requests:
    cpu: 100m
    memory: 64Mi
  limits:
    cpu: 500m
    memory: 128Mi
discover:
  resources:
    - limits:
        cpu: 500m
        memory: 128Mi
    - requests:
        cpu: 100m
        memory: 128Mi
