initContainers:
  - name: velero-plugin-for-aws
    image: velero/velero-plugin-for-aws:v1.8.2
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - mountPath: /target
        name: plugins
  - name: velero-plugin-for-csi
    image: velero/velero-plugin-for-csi:v0.6.2
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - mountPath: /target
        name: plugins

configuration:
  backupStorageLocation:
    - name: minio
      provider: aws
      bucket: backup
      default: true
      accessMode: ReadWrite
      config:
        region: de
        s3Url: http://192.168.11.11:9001
        s3ForcePathStyle: true
      defaultVolumesToRestic: true
credentials:
  useSecret: true
  existingSecret: "velero-s3-credentials"
snapshotsEnabled: false
